#### GET
GET http://localhost:4000/api/profile

###PUT
PUT http://localhost:4000/api/profile/1
Content-Type: application/json

{
    "real_name":"Eric Profile False",
    "description":"Perfil 1",
    "age":18 , 
    "user_id": 1
}

#### DELETE
DELETE http://localhost:4000/api/users/1



#### POST USER
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "name":"Eric Andres",
    "email": "EricAndresFariña@gmail.com",
    "password": "123123"
}

#### POST PROFILE
POST http://localhost:4000/api/profile
Content-Type: application/json

  {
    "real_name":"Eric Profile",
    "description":"Perfil 1",
    "age":18 , 
    "user_id": 1
  }


#### POST TASK
POST http://localhost:4000/api/tasks
Content-Type: application/json

{
    "title":"Task One",
    "description":"Es Verdadero",
    "isComplete":true,
    "profile_id":2
}



###POST LABEL
POST http://localhost:4000/api/label
Content-Type: application/json

{
  "name":"Urgente"
}

#### POST LABELTASK
POST http://localhost:4000/api/labeltask
Content-Type: application/json

{
  "task_id":1,
  "label_id":1
}




